Develop
n-e-t-t-u-n-o/yard-frontend pull request #2
Opened 2017-06-13 20:05 UTC by n-e-t-t-u-n-o

Совсем заморочился с футером уже, но хочу знать, где могут быть ошибки

2017-06-13 21:25 UTC, imevro requested changes
https://rawgit.com/n-e-t-t-u-n-o/yard-frontend/b7c68faad579bea003706ba56b6201a75ae66f0f/complexes.html

1) https://www.dropbox.com/s/yqkdhz2pku0lm64/Screenshot%202017-06-14%2000.23.59.png?dl=0
2) у кнопки скругление не то
3) горизонтальный скролл у страницы
4) https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fn-e-t-t-u-n-o%2Fyard-frontend%2Fb7c68faad579bea003706ba56b6201a75ae66f0f%2Fcomplexes.html

2017-06-14 13:02 UTC, n-e-t-t-u-n-o commented
Поправил все четыре пункта. Осталось непонимание, почему в футере оба ряда по полям колонок слегка не совпадают.

2017-06-14 14:36 UTC, imevro requested changes

2017-06-14 14:36 UTC, evgenyrodionov commented on complexes.html
> +  <header class="siteheader">
зачем префикс сайт

2017-06-14 14:36 UTC, evgenyrodionov commented on complexes.html
> +  <header class="siteheader">
и если это префикс, то почему он не отделен тире как site-header?

2017-06-14 14:36 UTC, evgenyrodionov commented on complexes.html
> +  <header class="siteheader">
но лучше без него

2017-06-14 14:36 UTC, evgenyrodionov commented on complexes.html
> +    <div class="siteheader-container between-lg container">
не смешивай сетку и свои классы

2017-06-14 14:36 UTC, evgenyrodionov commented on complexes.html
> +        <h4 class="footer-block-title">ООО &laquo;Ярд&raquo;</h4>
что за блок

2017-06-14 14:36 UTC, evgenyrodionov commented on complexes.html
> +        <p class="footer-imprint-text">ОГРН 1175074002531</p>
что за импринт

2017-06-14 14:36 UTC, evgenyrodionov commented on styles/styles.css
> +.discover-card:HOVER {
:НЕ НАДО ТАК КРИЧАТЬ

2017-06-15 07:42 UTC, n-e-t-t-u-n-o commented
Гм. В кэше rawgit зависла версия с прилипшим к потолку логотипом, на самом деле это не так.

2017-06-15 10:04 UTC, imevro requested changes

2017-06-15 10:04 UTC, evgenyrodionov commented on complexes.html
> +      <div class="container">
Лучше вынеси один общий контейнер за пределы карточек (.container > .card*3)

2017-06-15 13:10 UTC, imevro requested changes

2017-06-15 13:10 UTC, evgenyrodionov commented on complexes.html
> +      <a class="discover-card-link" href=#>
почему дискавер? И зачем постфикс линк?

2017-06-15 13:11 UTC, n-e-t-t-u-n-o commented on complexes.html
> +      <a class="discover-card-link" href=#>
почему дискавер — потому что предположил, что могут быть и другие карточки

2017-06-15 17:50 UTC, merged